<?xml version="1.0" encoding="utf-8"?><Database Name="BowmarPolls" Class="BowmarPollsDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\BowmarPolls.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BowmarPollsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Polls" Member="Polls">
    <Type Name="Poll">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Association Name="Poll_PollElement" Member="PollElements" ThisKey="id" OtherKey="poll_id" Type="PollElement" />
    </Type>
  </Table>
  <Table Name="dbo.PollElement" Member="PollElements">
    <Type Name="PollElement">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="poll_id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Poll_PollElement" Member="Poll" ThisKey="poll_id" OtherKey="id" Type="Poll" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Services" Member="Services">
    <Type Name="Service">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="current_poll" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ClientParticipation" Member="ClientParticipations">
    <Type Name="ClientParticipation">
      <Column Name="client_id" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="poll_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>